Repository filecoin-project/filecoin-docs, pull requests merged in 2020-07, with the labels that each got.

#115 Mining page expansions
  docs/mine/mining.md
Labels: Content Improvement

#158 Adds documentation for building filecoin application docs
  docs/.vuepress/config.js
  docs/how-to/build-filecoin-web-applications-with-textile-and-react.md
  docs/how-to/store/large-files.md
  package-lock.json
Labels: documentation

#191 Add information about lotus-miner set-addrs
  docs/mine/connectivity.md
Labels: New Content, documentation
